name: Rust

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: cargo build --release

    - name: compress
      run: tar czf wysiwyg.tar.gz -C target/release wysiwyg

    - name: create release
      id: create
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: release ${{ github.ref_name }}

    - name: upload release
      id: upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create.outputs.upload_url }}
        asset_path: ./wysiwyg.tar.gz
        asset_name: wysiwyg.tar.gz
        asset_content_type: application/gzip
